<?php

// SECURITY: Don't allow direct calls to this file outside the context of HelpSpot
if (! defined('cBASEPATH')) {
    die();
}

/* EDITING NOTES
1. Some strings contain %s symbols, these must be maintained
2. Any single quotes must be preceded by a slash like this:  \'  ex: there\'s
3. If you modify this file, be sure to back it up in case you overwrite it during an upgrade by accident
*/

define('lg_request_pagetitle','Anfrage erstellen');
define('lg_request_pagetitleedit','Anfrage verwalten');
define('lg_request_custid','Kunden ID');
define('lg_request_fname','Vorname');
define('lg_request_lname','Nachname');
define('lg_request_email','Email');
define('lg_request_phone','Telefon');
define('lg_request_headcust','Kunde');
define('lg_request_note','Notiz');
define('lg_request_newrequest','Neue Anfrag');
define('lg_request_batchreply','Batch Antwort');
define('lg_request_customer','Kunde'); //used sep from above
define('lg_request_customer_edit', 'Edit');
define('lg_request_livelookup','Live Lookup');
define('lg_request_starttimer', 'Start Timer');
define('lg_request_stoptimer', 'Stop Timer');
define('lg_request_timetrackeroptions', 'Options');
define('lg_request_timetracker','Zeiterfassung');
define('lg_request_timeevents','Time Events');
define('lg_request_timeevents_for','For Date');
define('lg_request_timeevents_entered','Entered On');
define('lg_request_timetrackerdel','Löschen');
define('lg_request_timetrackerempty','Keine Zeit Events vorhanden');
define('lg_request_timehrmin','hh:mm:ss');
define('lg_request_timedesc','Beschreibung');
define('lg_request_billable','Verrechenbar');
define('lg_request_timedelcheck','Möchten Sie diesen Log Eintrag wirklich entfernen?');
define('lg_request_logtime','Zeit Log');
define('lg_request_headreqnotes','Anfragenhistorie');
define('lg_request_closed','Geschlossen');
define('lg_request_showing','Sichtbar');
define('lg_request_show','Anzeigen');
define('lg_request_fullview','Gesamte Historie');
define('lg_request_publicview','Öffentliche Notizen');
define('lg_request_justnotes','Nur Notizen');
define('lg_request_fileview','Dateien');
define('lg_request_cancel','Entfernen');
define('lg_request_contactedvia_short', 'Via');
define('lg_request_contactedvia','Kontaktiert via');
define('lg_request_category','Kategorie');
define('lg_request_notedrafts','Entwurfe');
define('lg_request_attachbox', 'Click or drag/drop to attach');
define('lg_request_fileuploadtab','Anhang');
define('lg_request_er_fileupload','Fehler! Fehler! Die Datei ({filename}) ist zu gross um diese herauszuladen. Bitte vergewissern Sie sich, dass die Datei kleiner als {mb} MB ist.');
define('lg_request_reattachedfile','Angehängte Datei');
define('lg_request_notifystafftab','Staff benachrichtigen');
define('lg_request_addstaff','Staff auswählen');
define('lg_request_cc','Benachrichigt');
define('lg_request_appresponse','Antworten');
define('lg_request_searchresponses','Suche: Antworten');
define('lg_request_insertkblink','Wissenseintrag');
define('lg_request_kbprivate','Privat');
define('lg_request_assignedto','zugewiesen an');
define('lg_request_assignedto_change','Zuweisen...');
define('lg_request_reportingtags','Reporting Tags');
define('lg_request_isurgent','Dringend');
define('lg_request_isnoturgent', 'Mark Urgent');
define('lg_request_status','Status');
define('lg_request_custupdate','öffentlich');
define('lg_request_custupdatepriv','Privat');
define('lg_request_custupdateexternal','Extern');
define('lg_request_privdescexp','Nur Staff, nicht sichtbar für Kunde');
define('lg_request_extdescexp','Email an externen Kontakt, nicht sichtbar für Kunde');
define('lg_request_sendemailfrom','Versendet von');
define('lg_request_emailsubject','Emailetreff');
define('lg_request_emailreply','Antwort an');
define('lg_request_emailcc','Cc');
define('lg_request_emailbcc','Bcc');
define('lg_request_emailto','To');
define('lg_request_addtoemail','An Emailadresse hinzufügen');
define('lg_request_addccemail','CC Emailadresse hinzufügen');
define('lg_request_addbccemail','BCC Emailadresse hinzufügen');
define('lg_request_subscribers','Benachrichtigter Staff');
define('lg_request_subjectdefaultnew','Information zu Ihrer Anfrage');
define('lg_request_subjectdefault','Aktualisierung zu Ihrer Anfrage');
define('lg_request_showingx','Letzte %s von %s Aktualisierungen werden dargestellt.');
define('lg_request_showingxdirect','Zeige 1 von %s Aktualisierungen.');
define('lg_request_showall','Alle darstellen');
define('lg_request_create','Anfrage erstellen');
define('lg_request_update','Anfrage aktualisieren');
define('lg_request_emailcustomermsg','Kunde wird nicht benachrichtigt');
define('lg_request_emailcustomermsg_active','Kunde <strong>wird</strong> benachrichtigt');
define('lg_request_updatenclose','Aktualisieren und schliessen');
define('lg_request_create_close','Erstellen und schliessen');
define('lg_request_batchremove','entfernen');
define('lg_request_batch','Begin Batch Antworten');
define('lg_request_batch_close','Begin Batch Antworten und schliesse Anfragen');
define('lg_request_batchconfirm','Wirklich alle Anfragen beantworten?');
define('lg_request_batchlist','Anfragen in Batch');
define('lg_request_historysearch','Historiesuche');
define('lg_request_searchtype','Suche Typ');
define('lg_request_sidebar','Kundensuche');
define('lg_request_search1','Allgemeinesuche');
define('lg_request_search2','Email Adresse übereinstimmend');
define('lg_request_search3','Name übereinstimmend');
define('lg_request_search4','KundenID übereinstimmend');
define('lg_request_search5','Email Domain übereinstimmend');
define('lg_request_search6','Vorname übereinstimmend');
define('lg_request_search7','Nachname übereinstimmend');
define('lg_request_search8', 'Search');
define('lg_request_search9', 'Results');
define('lg_request_searchnomatch','keine Übereinstimmung');
define('lg_request_insertdata','Kundeninformation hinzufügen');
define('lg_request_mergerequest','Zusammenfügen');
define('lg_request_returntosearch','zurück zur Suche');
define('lg_request_fb_reqadded','Anfrage hinzugefügt');
define('lg_request_fb_requpdated','Anfrage aktualisiert');
define('lg_request_fb_requpdatenclosed','Anfrage aktualisiert und geschlossen');
define('lg_request_batchwarninghead','Batch Information');
define('lg_request_batchwarning','Custom field, Category, and Assignment changes here will override existing data for all selected requests. Empty custom fields will not override existing custom field information.');
define('lg_request_batchwarning2','Filter erstellen für spätere Aktualisierungen');
define('lg_request_reqid','ID');
define('lg_request_pushdetailsbox','Anfrage Push Detail');
define('lg_request_pushcomment','Kommentar (optional)');
define('lg_request_print','Druckansicht');
define('lg_request_reminders','Erinnerung');
define('lg_request_viewinportal','In Portal darstellen');
define('lg_request_savedraft','Entwurf speichern');
define('lg_request_passwords','Zugriffsschlüssel darstellen');
define('lg_request_add_notifications','Benachrichtigung hinzufügen');
define('lg_request_subscribebutton','Benachrichtigen');
define('lg_request_subscribedbutton','Benachrichtigt');
define('lg_request_reminderbutton','Erinnerung setzen');
define('lg_request_merge','Beginnen mit zusammenfügen');
define('lg_request_merged','Zusammengefügt');
define('lg_request_mergeid','Anfragen ID um zusammenzufügen');
define('lg_request_mergebutton','Anfragen Zusammenfügen');
define('lg_request_mergeconfirm','Zusammenfügen bestätigen');
define('lg_request_mergebadid','Diese Anfrage ID ist nicht korrekt.');
define('lg_request_mergetoself','Sie können eine Anfrage nicht mit sich selber zusammenfügen');
define('lg_request_mergeconftext1','Aktuelle Anfrage zusammenfügen');
define('lg_request_mergeconftext2','in');
define('lg_request_mergeconfirmid','Anfragen ID');
define('lg_request_mergeconfirmopen','Eröffnet am');
define('lg_request_mergeconfbutton','Zusammenfügen bestätigen');
define('lg_request_mergefailed','Zusammenfügen fehlgeschlagen');
define('lg_request_reqpush','Anfragen Push');
define('lg_request_reqpushok','The request has been pushed');
define('lg_request_push','Push');
define('lg_request_pushselect','Push zu');
define('lg_request_pushdetails','Details');
define('lg_request_quotepublic','Quote Public History');
define('lg_request_movetotrash','In Papierkorb verschieben');
define('lg_request_trashconfirm','Möchten Sie diese Anfrage in den Papierkorb verschieben?');
define('lg_request_log','Log');
define('lg_request_from','Von');
define('lg_request_sent','Versendet');
define('lg_request_to','An');
define('lg_request_viaportal','Via Portal');
define('lg_request_subject','Betreff');
define('lg_request_emailoptions', 'Email Options');
define('lg_request_fb_subscribed','Sie werden nun benachrichtigt');
define('lg_request_fb_unsubscribed','Sie werden nicht mehr benachrichtigt');
define('lg_request_fb_unpublic','Anfragenhistorie element wurde entfernt');
define('lg_request_fb_public','Anfragenhistorie wurde öffentlich gesetzt');
define('lg_request_fb_spam','Anfrage als SPAM deklariert');
define('lg_request_accesskey','Zugriffsschlüssel');
define('lg_request_showheaders','Header anzeigen');
define('lg_request_showsource','Quelle anzeigen');
define('lg_request_reopen','Anfrage erneut öffnen');
define('lg_request_public','Notiz auf Privat setzen');
define('lg_request_makepublic','Notiz auf Öffentlich setzen');
define('lg_request_makepubliccheck','Info: Diese Nachricht wird im Kundenportal verfügbar sein, jedoch NICHT dem Kunden als Email zugestellt.');
define('lg_request_makelog','Anfragenhistorie');
define('lg_request_makepublog','Öffentlich gesetzt');
define('lg_request_makeprivlog','Privat gesetzt');
define('lg_request_publicrss','Öffentlich');
define('lg_request_quote','Zitieren');
define('lg_request_forward','Weiterleiten');
define('lg_request_directlink','Direkter Link');
define('lg_request_converttorequest','Zu Anfrage konvertieren');
define('lg_request_converttorequestconfirm','Dieses Element wirklich als neue Anfrage konvertieren?');
define('lg_request_publiccheck','Möchten Sie diese Nachricht wirklicht entfernen?');
define('lg_request_deleterem','löschen');
define('lg_request_trashbox','Diese Anfrage befindet sich zur Zeit im Papierkorb. Jegliche Aktualisierung entfernt die Anfrage aus dem Papierkorb.');
define('lg_request_spambox', 'MARKED AS SPAM: This request must be placed in a different status before it can be updated.');
define('lg_request_fb_reqerror','Beim Hinzufügen der Anfrage wurde ein Problem gefunden.');
define('lg_request_fb_reqsmerged', 'Requests merged');
define('lg_request_fb_remdeleted','Erinnerung gelöscht');
define('lg_request_fb_fromhdinprocess','Diese Anfrage wird bereits bearbeitet von:');
define('lg_request_fb_history_limit', "This request has reached its request history limit - any future notes will be discarded. For questions about this, support can be reached at <a href=\"mailto:customer.service@userscape.com\">customer.service@userscape.com</a>.");
define('lg_request_er_closewhileactive','Eine Anfrage mit dem Status "Aktiv" kann nicht gelöscht werden.');
define('lg_request_er_choosestatus','Abschlussstatus auswählen');
define('lg_request_er_nocategory','Diese Anfrage muss einer Kategorie zugeordnet werden');
define('lg_request_er_spam', 'Requests marked as spam can\'t be updated.');
define('lg_request_er_nocustinfo','Es werden Kundeninformationen benötigt');
define('lg_request_er_nocontactvia','Sie müssen die Kontaktmöglichkeit auswählen');
define('lg_request_er_noexternalto','Bitte Empfänger für externe Notiz definieren');
define('lg_request_er_nonotewfile','Sie benötigen eine Notiz zu Ihren Dateianhängen');
define('lg_request_er_nonotecreate','Sie benötigen eine Notiz um eine Anfrage zu erstellen');
define('lg_request_er_nonoteattach','Notizen benötigen eine Nachricht zu den Anhängen.');
define('lg_request_er_customempty','Bitte ausfüllen');
define('lg_request_er_decimal','Bitte eine dezimale Nummer angeben');
define('lg_request_er_number','Bitte eine Numer angeben');
define('lg_request_er_regex','Bitte im richtigen Format angeben');
define('lg_request_er_delreminder','Beim löschen der Erinnerung ist ein Fehler aufgetreten.');
define('lg_request_er_unpublic','Ein Fehler ist aufgetreten, die Notiz wurde nicht aus der öffentlichen Ansicht entfernt');
define('lg_request_er_makepublic','Ein Fehler ist aufgetreten, die Notiz konnte nicht öffentlich gemacht werden');
define('lg_request_er_emailsenderror', 'EMAIL ERROR: An email failed to send.');
define('lg_request_er_emailcusterror','EMAIL FEHLER: Die Mailadresse des Kunden löste ein Fehler aus.');
define('lg_request_er_emailccerror','EMAIL Fehler: Die CC Mailadresse führt zu einem Fehler. Das Mailsystem gibt folgenden Fehler zurück');
define('lg_request_er_emailexterror','EMAIL Fehler: Die externe Mailadresse führt zu einem Fehler. Das Mailsystem gibt folgenden Fehler zurück');
define('lg_request_mark_todo','Um diesen Effekt zu erhalten...');
define('lg_request_mark_type','Eingeben...');
define('lg_request_mark_full','Kompletter Syntax anzeigen');
define('lg_request_viewfull','ganze Grösse');
define('lg_request_view','View');
define('lg_request_fwd','Fwd');
define('lg_request_unkownid','unbekannte AnfragenID');
define('lg_request_not_a_valid_email', 'keine gültige Email addresse');
define('lg_request_lose_attachment', 'Wechseln des Notizentyp bewirkt, dass die Anhänge erneut hochgeladen werden müssen.');
define('lg_request_drop_here', 'Dateien hier ablegen um diese zu uploaden');
define('lg_request_pin', 'Pin');
define('lg_request_pinned', 'Pinned');
define('lg_admin_thermostat_label_see_results', 'See Survey Results');
define('lg_request_close', 'Close');
define('lg_request_transfer_warning',"You are assigning this request to a category you do not have access to. After update you will no longer be able to view this request");
define('lg_request_missing_attachment', 'The file %s was not found on the disk, please attach it again.');
define('lg_request_er_tag_mismatch', 'A variable you inserted is mismatched. Please make sure that all variables you used in your note are wrapped in two curly brackets. Like this: {{ $var }}');
define('lg_request_drilldown_value_error', 'no longer has a valid value. This is most likely due to the removal of options by an administrator. Please reset this field to a valid value.');
define('lg_request_translate_history', 'Translate');
define('lg_request_translation_loading', 'Loading Translation');
define('lg_request_translation_error_title', 'Translation Failed');
define('lg_request_translation_error', 'Your request history item failed to translate');